config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :blog_posts

  root 'blog_posts#index'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	has_many :comments
	belongs_to :user
	has_attached_file :theme, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :theme, :content_type => /\Aimage\/.*\Z/
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog_post
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blog_posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :username) }

  devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :current_password, :username) }
 end

  
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry, :user_id, :theme)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :blog_post_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<form role="form">
  <div class="form-group">
    <%= f.text_field :title, placeholder: "Your Title Goes Here", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group">
    <%= f.text_area :blog_entry, placeholder: "Write something here...", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :theme %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>
</form>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogging About The End of the World</h1>

<%= link_to 'New Blog post', new_blog_post_path, class: "btn btn-info", id: "ugly-button" %>

<br>
  <div class="row">
    <% @blog_posts.each do |blog_post| %>
      <div class="col-md-4">
        <div class="well">
        <h3><%= blog_post.title %></h3>
        <p><em>by: <%= blog_post.user.username %></em></p>
        <p><%= blog_post.blog_entry[0..50] %><%= link_to '...', blog_post %></p>
        <%= link_to 'Get Closer', blog_post, class: "btn btn-primary" %>
        <%= link_to 'Zombify', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
        <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    </div>
    <% end %>
  </div>

<br>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">

	<h2><%= @blog_post.title %></h2>
	<em>by: <%= @blog_post.user.username %></em>

<hr>

<div class="row" id="entry">
		<% if @blog_post.theme_file_name != nil %>
			<div class="col-md-3">
			<%= image_tag @blog_post.theme.url(:medium), class: "img-responsive" %>
		</div>
		<% end %>
  	<%= @blog_post.blog_entry %>
</div>
<br>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>

<hr>

<%= render 'comments/form' %>

<hr>

<% @blog_post.comments.each do |c| %>
	<h6><%= c.user.username %> said...</h6>
	<p><%= c.comment_entry %></p>
	<small><%= c.created_at.strftime("%m/%d/%Y at %I:%M%p") %></small>
<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.text_area :comment_entry, placeholder: "Put your comment here..." %>
  </div>
  <div class="field">
    <%= f.hidden_field :blog_post_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Comments</h1>

<%= link_to 'New Comment', new_comment_path, class: "btn btn-info", id: "ugly-button" %>

<div class="row">
    <% @comments.each do |c| %>
    <div class="col-md-4">
      <div class="well" id="comment">
        <h4><%= c.user.username %></h4>
        <p><%= c.comment_entry %></p>
        <%= link_to 'Get Closer', c, class: "btn btn-primary" %>
        <%= link_to 'Zombify', edit_comment_path(c), class: "btn btn-warning" %>
        <%= link_to 'Destroy', c, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.user.email %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Eater|Comfortaa' rel='stylesheet' type='text/css'>
  <title>Blogenstein</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Your Have No Home Now</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav navbar-nav navbar-right">
      	<% if user_signed_in? %>
        <li id="white"><a href="https://www.youtube.com/watch?v=fYso3yVCI4Q" target="_blank">Don't Get Eaten, <%= current_user.username %>!</a></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container"> 
<%= yield %>
</div>

</body>
</html>